HTTP and WS RPC APIs to listen on the same socket
LimeChain/java-host pull request #133
Opened 2023-08-17 08:06 UTC by ablax

* Websocket configuration to differentiate http and ws request
 * Remove HttpRpc

Closes #132

2023-08-17 08:10 UTC, vikinatora requested changes
Please rename everything that is "ws" to "rpc". For example `WebSocketConfig` should be `RpcConfig`,

2023-08-17 08:21 UTC, vikinatora requested changes

2023-08-17 08:21 UTC, vikinatora commented on src/main/java/com/limechain/Main.java
> +        RpcApp wsRpc = new RpcApp();
`wsRpc` can be renamed to `rpcApp`

2023-08-17 08:21 UTC, vikinatora commented on src/main/java/com/limechain/lightclient/LightClient.java
> +    private final RpcApp wsRpc;
`wsRpc` can be renamed to `rpcApp`

2023-08-17 08:21 UTC, vikinatora commented on src/main/java/com/limechain/lightclient/LightClient.java
> +    public LightClient(String[] cliArgs, RpcApp wsRpc) {
`wsRpc` can be renamed to `rpcApp`

2023-08-17 08:21 UTC, vikinatora commented on src/test/java/com/limechain/lightclient/LightClientTest.java
> +    private RpcApp wsRpc;
`wsRpc` can be renamed to `rpcApp`

2023-08-17 08:21 UTC, vikinatora commented on src/test/java/com/limechain/lightclient/LightClientTest.java
> +    private RpcApp wsRpc;
`wsRpc` can be renamed to `rpcApp`

2023-08-17 08:21 UTC, vikinatora commented on src/test/java/com/limechain/lightclient/LightClientTest.java
> +        wsRpc = mock(RpcApp.class);
`wsRpc` can be renamed to `rpcApp`

2023-08-17 10:21 UTC, vikinatora approved these changes

2023-08-17 10:27 UTC, merged

2024-03-07 16:20 UTC, Jess25051980 approved these changes

2024-03-07 16:20 UTC, Jess25051980 approved these changes